name: The Burn Method
favicon: null
layout_spectrum: 0.48854
typography_spectrum: 1
title: The Burn Method
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#72519b'
    - '#f36756'
    - '#baaace'
    - '#797979'
  brandStrength: 0.6875
  lightness: 0.8447208211291581
  saturation: 0.5243564711418003
  rhythmicContrast: 0.7384031233377755
purpose: []
