name: The Burn Method
favicon: null
layout_spectrum: 0.48854
typography_spectrum: 1
title: The Burn Method
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#72519b'
    - '#f36756'
    - '#baaace'
    - '#797979'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
